worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # API Gateway routing rules
    server {
        listen 5000;
        server_name localhost;

        # Disable max request body size limits
        client_max_body_size 0;

        # Auth Service Routing
        location /api/auth/ {
            proxy_pass http://auth-service:5001/api/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Ingestion Service Routing (Footprints write and history read)
        location /api/footprints {
            proxy_pass http://ingestion-service:5002/api/footprints;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Leaderboard Service Routing
        location /api/leaderboard {
            proxy_pass http://leaderboard-service:5003/api/leaderboard;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
